const $=(s,c=document)=>c.querySelector(s);const $$=(s,c=document)=>Array.from(c.querySelectorAll(s));
const header=$('#header'),progress=$('#progress'),menuBtn=$('#menuBtn'),nav=$('#nav'),backTop=$('#backTop'),year=$('#year');if(year)year.textContent=new Date().getFullYear();
function state(){const d=document.documentElement;const h=d.scrollHeight-innerHeight;const p=h>0?Math.min(100,(scrollY/h)*100):0;if(progress)progress.style.width=p+'%';if(header)header.classList.toggle('scrolled',scrollY>10);if(backTop)backTop.classList.toggle('show',scrollY>650)}addEventListener('scroll',state,{passive:true});addEventListener('resize',state);state();
if(menuBtn&&nav){menuBtn.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuBtn.setAttribute('aria-expanded',open)});$$('a',nav).forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menuBtn.setAttribute('aria-expanded','false')}))}
$$('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href');if(!id||id==='#')return;const t=$(id);if(!t)return;e.preventDefault();t.scrollIntoView({behavior:'smooth',block:'start'})}));
if(backTop)backTop.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
const disclosure=$('.disclosure'),toggle=$('.toggle');if(disclosure&&toggle){toggle.addEventListener('click',()=>{disclosure.classList.toggle('closed');const p=disclosure.querySelector('p');const b=toggle.querySelector('b');const closed=disclosure.classList.contains('closed');if(p)p.style.display=closed?'none':'block';if(b)b.textContent=closed?'+':'−'})}
$$('.faq-item button').forEach(btn=>btn.addEventListener('click',()=>btn.closest('.faq-item').classList.toggle('open')));
const reveals=$$('.reveal');if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});reveals.forEach(el=>io.observe(el))}else reveals.forEach(el=>el.classList.add('visible'));
